// This file was autogenerated by C:\Projects\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../BuildWithClosure/src/aloy/app.js', ['aloy.App'], ['aloy.soy']);
goog.addDependency('../../../BuildWithClosure/src/aloy/plugin.js', ['aloy.Plugin'], ['goog.dom', 'goog.dom.classes', 'goog.events']);
goog.addDependency('../../../BuildWithClosure/src/aloy/ui/paginator/paginator.js', ['aloy.ui.Paginator'], ['aloy.ui.soy.paginator', 'goog.dom.classes', 'goog.dom.dataset', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.ui.IdGenerator']);
goog.addDependency('../../../BuildWithClosure/src/aloy/ui/paginator/paginator.soy.js', ['aloy.ui.soy.paginator'], ['soy', 'soy.StringBuilder']);
goog.addDependency('../../../BuildWithClosure/src/aloy/ui/tagger/TaggerRenderer.js', ['aloy.ui.TaggerRenderer'], ['aloy.ui.soy.Tagger', 'goog.string', 'goog.ui.ContainerRenderer', 'goog.ui.FlatButtonRenderer', 'soy']);
goog.addDependency('../../../BuildWithClosure/src/aloy/ui/tagger/export.js', ['aloy.ui.TaggerExport'], ['aloy.ui.Tagger']);
goog.addDependency('../../../BuildWithClosure/src/aloy/ui/tagger/tagger.js', ['aloy.ui.Tagger', 'aloy.ui.TaggerConfig', 'aloy.ui.TaggerModel'], ['aloy.ui.TaggerRenderer', 'goog.ui.Button', 'goog.ui.Container']);
goog.addDependency('../../../BuildWithClosure/src/aloy/ui/tagger/tagger.soy.js', ['aloy.ui.soy.Tagger'], ['soy', 'soy.StringBuilder']);
goog.addDependency('../../../BuildWithClosure/src/libs/soy/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency('../../../BuildWithClosure/src/soyTemplates/first.soy.js', ['aloy.soy'], ['soy', 'soy.StringBuilder']);
